name: deploy-on-push-main

on: 
  push: 
    branches:
      - main
      
jobs:
  deploy:
    runs-on: self-hosted
    steps: 
      - working-directory: /var/www/html
        run: git clone https://github.com/Sander470/portfolio.git
